---
- include: dependency.yml

- name: "Pull down source for Whisper, Carbon, and Graphite Web"
  git: repo={{ item.repo }}
       dest=/usr/local/src/{{ item.name }}
       version={{ item.version }}
  with_items:
    - { name: "whisper", repo: "https://github.com/graphite-project/whisper.git", version: "{{ graphite_whisper_version }}" }
    - { name: "carbon", repo: "https://github.com/graphite-project/carbon.git", version: "{{ graphite_carbon_version }}" }
    - { name: "graphite-web", repo: "https://github.com/graphite-project/graphite-web.git", version: "{{ graphite_web_version }}" }

- include: statsd.yml
- include: whisper.yml
- include: carbon.yml
- include: graphite-web.yml
